apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: app1
  namespace: argocd
spec: 
  destination: 
    namespace: backend
    server: "https://kubernetes.default.svc"
  source:
    path: apps/app1
    repoURL: git@github.com:davinderrai/test-argo-examples.git
    targetRevision: HEAD
    directory:
      recurse: true    
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
      - CreateNamespace=true