apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: app2
  namespace: backend
spec: 
  destination: 
    namespace: backend
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: apps/app2
    repoURL: git@github.com:davinderrai/test-argo-examples.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true